### ISSUE TITLE
Resolve not working

### ISSUE THREAD

**Issue by vivekimsit** [solkimicreb/react-stax#1]
First of all thanks a lot for making effort to create this project.
I have just started working on it and can see the clear logic while
writing components.

The only issue I am facing is that my route resolver is not working,
I tried to go through your example but no luck.

The code is [here](https://github.com/vivekimsit/honeypot/blob/master/src/App.js#L63)

Thanks,

**Comment by solkimicreb** [comment]
Hi!

This project is not officially released yet, you will have to wait a little bit more before you can use it. Sorry to let you down ): The API changed a bit since my streams and I did not finish the final documentation yet. I will try to be quick about the finishing the project, but it takes a lot of time 🙂 

 (In the final version resolving is done in the `onRoute` handler).

**Comment by vivekimsit** [comment]
Hi,

No worried you are doing a great work, I have found some temporary fix.

On a side note I requested you before if you want you can let me collaborate,
I will more than happy to do this because I really like your way of programming.

Feel free to setup a gitter or DM me if you want to include me.

Thanks,

**Comment by solkimicreb** [comment]
This is not yet released, but thanks for your input 🙂
